### ISSUE TITLE
Where can I find the Dockerfiles?

### ISSUE THREAD

**Issue by tobsan** [Linaro/lava#1]
I was trying to see how the images on Dockerhub gets built, but there are no Dockerfiles published there, and they don't seem to be here either. Is there a place where I can find them? Could they be added to the repo?

**Comment by tobsan** [comment]
I'm an idiot, and I just found the GitLab repos, sorry about this.

**Comment by fboudra** [comment]
https://git.lavasoftware.org/lava/pkg/docker
